version: '3.1'
services:
  db:
    image: postgres:17-alpine
    container_name: archivio_database
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: archivio
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

#  backend:
#    container_name: archivio-backend-application
#    build:
#      context: .
#      dockerfile: Dockerfile
#    restart: always
#    environment:
#      PROFILE: dev
#      DATABASE_URL: jdbc:postgresql://db:5432/archivio
#      DATABASE_USERNAME: postgres
#      DATABASE_PASSWORD: root
#    depends_on:
#      - db
#    ports:
#      - "8080:8080"

volumes:
  pgdata: