services:

  # Database Service (Postgres Container)
  db:
    image: postgres:17-alpine
    container_name: database
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: archivio
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 5s
      retries: 5

  # Backend Service (Spring Boot Container)
  backend:
    container_name: backend
    build:
      context: ./archivio-backend
      dockerfile: Dockerfile
    restart: always
    environment:
      SPRING_PROFILE: docker
      DATABASE_URL: jdbc:postgresql://db:5432/archivio
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: root
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"

  # Frontend (Angular Container)
  frontend:
    container_name: frontend
    build:
      context: ./archivio-frontend
      dockerfile: Dockerfile
    restart: always

    depends_on:
      - backend

    ports:
      - '127.0.0.1:5000:80'

volumes:
  pgdata:
